### ISSUE TITLE
What is the experiments branch doing?

### ISSUE THREAD

**Issue by E3V3A** [kryptoslogic/nucleus#1]
Hi! Cool project, 
but what is the `experiment` branch doing?

**Comment by j-mie** [comment]
The `experiment` branch currently fixes a couple of bugs with sections and bindings, you're able to access the contents of a section via the bindings now. We have some other plans for this branch too but haven't had much time yet. We'll likely do our changes to Nucleus, get our intended use case working and then release a blog post.
